---
- name: Add Docker repository.
  yum_repository:
    file: docker-ce
    name: docker-ce
    description: 'Docker CE Stable - $basearch'
    baseurl: "{{ docker.centos_repo }}"
    enabled: 1
    gpgcheck: 1
    gpgkey: "{{ docker.centos_key }}"

- name: Install Docker.
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: Start Docker service.
  service:
    name: docker
    state: started
    enabled: true

- name: Verify if docker-compose is installed.
  stat:
    path: '/usr/bin/docker-compose'
  register: compose_installed

- name: Install Docker Compose.
  block:
  - name: Get variables for url.
    shell: echo "$(uname -s)-$(uname -m)"
    register: kernel_arch

  - name: Download Docker Compose binary.
    get_url:
      url: "{{ docker.compose_url }}/docker-compose-{{ kernel_arch.stdout }}"
      dest: /usr/bin/docker-compose
      mode: '0750'

  when: compose_installed.stat.exists == False
